version: '2.0'
services:
  app:
    build: .
    links:
      - mongo
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
      DISCORD_TOKEN: "${DISCORD_TOKEN}"
      TWITCH_CLIENTID: "${TWITCH_CLIENTID}"
      TWITCH_OAUTH: "${TWITCH_OAUTH}"
    volumes:
      - .:/app
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example